framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: '%env(DEFAULT_URI)%'

# En production, les paramètres ne sont plus confrontés aux `requirements` des
# routes lors de la génération d'une URL (réglage recommandé par Symfony en prod).
when@prod:
    framework:
        router:
            strict_requirements: null
