<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Phase A — Producer module foundation:
 * Create the `withdrawal_request` table.
 *
 * - PK UUID
 * - FK studio_id NOT NULL -> studio(id)
 * - FK requested_by_id NOT NULL -> user(id)
 * - FK reviewed_by_id NULL -> user(id)
 * - target_type ('film'|'serie'), target_id UUID
 * - status ('PENDING'|'APPROVED'|'REJECTED') default 'PENDING'
 * - composite index (target_type, target_id, status)
 * - PARTIAL UNIQUE index `uniq_withdrawal_pending` to enforce a single
 *   PENDING request per (target_type, target_id). Doctrine doesn't generate
 *   partial indexes, so we add it via raw SQL.
 *
 * En français : crée la table des demandes de retrait (un studio demande le
 * retrait d'un de ses contenus, un admin approuve ou rejette). La cible est
 * polymorphe (`target_type` + `target_id`) : il n'y a donc pas de clé
 * étrangère vers film ou serie. L'index unique partiel interdit deux demandes
 * PENDING pour le même contenu tout en conservant l'historique des demandes
 * traitées. Comme il est invisible pour l'ORM, `migrations:diff` propose
 * ensuite de le supprimer (DROP INDEX uniq_withdrawal_pending) : ligne à
 * retirer à la main (gotcha n° 16 de BACKEND_MEMORY.md).
 */
final class Version20260430100200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Phase A — Create withdrawal_request table with partial unique index on PENDING.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE withdrawal_request (
                id UUID NOT NULL,
                studio_id UUID NOT NULL,
                requested_by_id UUID NOT NULL,
                reviewed_by_id UUID DEFAULT NULL,
                target_type VARCHAR(10) NOT NULL,
                target_id UUID NOT NULL,
                reason TEXT NOT NULL,
                status VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
                reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                review_note TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX IDX_5E56F6D7446F285F ON withdrawal_request (studio_id)');
        $this->addSql('CREATE INDEX IDX_5E56F6D74DA1E751 ON withdrawal_request (requested_by_id)');
        $this->addSql('CREATE INDEX IDX_5E56F6D7FC6B21F1 ON withdrawal_request (reviewed_by_id)');
        $this->addSql('CREATE INDEX idx_withdrawal_target_status ON withdrawal_request (target_type, target_id, status)');

        $this->addSql('ALTER TABLE withdrawal_request ADD CONSTRAINT FK_5E56F6D7446F285F FOREIGN KEY (studio_id) REFERENCES studio (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE withdrawal_request ADD CONSTRAINT FK_5E56F6D74DA1E751 FOREIGN KEY (requested_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE withdrawal_request ADD CONSTRAINT FK_5E56F6D7FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');

        // Partial unique index: at most one PENDING request per target.
        // (Not generated by Doctrine — added natively for PostgreSQL.)
        $this->addSql("CREATE UNIQUE INDEX uniq_withdrawal_pending ON withdrawal_request (target_type, target_id) WHERE status = 'PENDING'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX uniq_withdrawal_pending');
        $this->addSql('ALTER TABLE withdrawal_request DROP CONSTRAINT FK_5E56F6D7FC6B21F1');
        $this->addSql('ALTER TABLE withdrawal_request DROP CONSTRAINT FK_5E56F6D74DA1E751');
        $this->addSql('ALTER TABLE withdrawal_request DROP CONSTRAINT FK_5E56F6D7446F285F');
        $this->addSql('DROP TABLE withdrawal_request');
    }
}
